const {
  SUPER_ADMIN_FULLNAME,
  SUPER_ADMIN_EMAIL,
  SUPER_ADMIN_PROFILE_IMAGE,
  SUPER_ADMIN_PASSWORD,
  SUPER_ADMIN_ROLE,
  SUPER_ADMIN_PHONE,
  SUPER_ADMIN_ADDRESS,
} = process.env;



const createAdmin